name: push_test.yml

on:
  push:
    branches:
      - 'main'
      - 'test1'
    paths:
      - 'test/**'
      
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      shell: bash
      run: echo "changes!"
