name: Test_Workflow

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0'
      test_run:
        required: true
        type: boolean
        default: false
      deploy_artefact:
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echo inputs
        run:  |
          echo "version: ${{  inputs.version  }}"
          echo "test_run: ${{  inputs.test_run  }}"
          echo "deploy_artefact: ${{  inputs.deploy_artefact  }}"
          
  paralel_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [1,2,3]
    steps:
      - uses: actions/checkout@v3
      - name: pararel test version ${{  matrix.versions  }}
        run: echo "Ping"
