name: Test_Workflow

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0'
      test_run:
        required: true
        type: boolean
        default: false
      deploy_artefact:
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo inputs
        run:  |
          echo "version: ${{  inputs.version  }}"
          echo "test_run: ${{  inputs.test_run  }}"
          echo "deploy_artefact: ${{  inputs.deploy_artefact  }}"
          echo "This is artifact" > artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_artifact
          path: artifact.txt
          
  test_run:
    if: ${{  inputs.test_run == true  }}
    needs: paralel_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "Test running..."
       
  paralel_test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [1,2,3]
    steps:
      - uses: actions/checkout@v3
      - name: pararel test version ${{  matrix.versions  }}
        env: 
          VERSION: ${{  matrix.versions  }}
        run: |
          sleep 15s
          echo "Ping from version $VERSION"

  download_artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build_artifact
      - name: Print artifact
        run: cat artifact.txt

  call_deploy_artifact:
    if: ${{  inputs.deploy_artefact == true  }}
    needs: test_run
    uses: ./.github/workflows/deploy_artifact.yml
    with: 
      version: ${{  inputs.version  }}
      
